#!/usr/bin/env bash
# PreToolUse hook: the vendored copies are generated, never edited.
#
# public/js/ and ShaderCarousel/components/three/a-frame-180-a-01.min.js are
# written by the `fs-vendor-sync` vite plugin from a-frame-shaderloader/js/
# (the git submodule and the jsdelivr CDN source). A hand edit there is
# overwritten on the next vite start AND fails src/vendorSync.test.ts.
#
# Edit/Write/MultiEdit on those paths: DENY (certain).
# Bash commands that look like they write there: ASK (heuristic — a read such
# as `cp public/js/x /tmp` would also match, so the user decides).
set -u

input=$(cat)
tool=$(printf '%s' "$input" | jq -r '.tool_name // ""')

# The boundary is "not part of a longer name": a `/` in an absolute path, a
# space or quote in a shell command.
VENDORED_RE='(^|[^A-Za-z0-9_.-])public/js/|(^|[^A-Za-z0-9_.-])ShaderCarousel/components/three/a-frame-180-a-01\.min\.js'
REASON='Vendored copy — generated by the fs-vendor-sync vite plugin. Edit the source in a-frame-shaderloader/js/ (the submodule) and re-run vite; vendorSync.test.ts fails on drift. Loaders 0.4/0.5/0.6 are FROZEN; new work goes in 0.8, additively.'

decide() {
  jq -n --arg d "$1" --arg r "$REASON" \
    '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: $d, permissionDecisionReason: $r}}'
  exit 0
}

case "$tool" in
  Edit|Write|MultiEdit|NotebookEdit)
    path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""')
    printf '%s' "$path" | grep -Eq "$VENDORED_RE" && decide deny
    ;;
  Bash)
    cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')
    if printf '%s' "$cmd" | grep -Eq "$VENDORED_RE"; then
      if printf '%s' "$cmd" | grep -Eq '(sed|perl)[[:space:]]+-[a-zA-Z]*i|>[[:space:]]*[^[:space:]]*public/js/|(^|[^a-z])(tee|cp|mv|rm|rsync|install)[[:space:]]|\.write|writeFile'; then
        decide ask
      fi
    fi
    ;;
esac
exit 0
