/**
 * Shared TSL code processing utilities used by tslToPreviewHTML and tslToShaderModule.
 * Handles import extraction, TDZ fix, body parsing, and channel resolution.
 */

import type { MaterialSettings } from '@/types';
import { sanitizeIdentifier } from '@/utils/nameUtils';

const CHANNEL_TO_PROP: Record<string, string> = {
  color: 'colorNode',
  emissive: 'emissiveNode',
  normal: 'normalNode',
  position: 'positionNode',
  opacity: 'opacityNode',
  roughness: 'roughnessNode',
};

interface TSLImports {
  tslNames: string[];
}

interface ProcessedBody {
  defLines: string[];
  channels: Record<string, string>;
}

/** Collect imported names from 'three/tsl'. */
function collectImports(tslCode: string, excludeFn = false): TSLImports {
  const tslNames: string[] = [];

  const tslImportRe = /import\s*\{([^}]+)\}\s*from\s*['"]three\/tsl['"]/g;
  let m: RegExpExecArray | null;
  while ((m = tslImportRe.exec(tslCode)) !== null) {
    for (const name of m[1].split(',').map(s => s.trim()).filter(Boolean)) {
      if (excludeFn && name === 'Fn') continue;
      if (!tslNames.includes(name)) tslNames.push(name);
    }
  }

  return { tslNames };
}

interface ExtractedFn {
  /** The statements inside the main `Fn(() => { ... })` wrapper. */
  body: string;
  /** Non-`three/tsl` import lines that precede the main Fn (preserved verbatim). */
  preambleImports: string[];
  /**
   * Module-scope declarations that precede the main Fn — e.g. the `hsl`/`toHsl`
   * helper `Fn`s graphToCode emits for the HSL color nodes. These are called
   * from inside the body, so dropping them produces a module that references an
   * undefined helper. Preserved verbatim and re-emitted at module scope.
   */
  preambleDecls: string[];
}

/**
 * Extract the body of the main `Fn(() => { ... })` wrapper, and preserve
 * everything that precedes it at module scope (non-`three/tsl` imports +
 * helper declarations). The main shader Fn is the empty-param `Fn(() => {`
 * (helpers use the param form `Fn(([...]) => {`, so `indexOf('Fn(() => {')`
 * lands on the shader, never a helper). The body is closed by brace-matching
 * from that point — robust to trailing module code and nested blocks, where the
 * old `lastIndexOf('});')` could mis-slice. (A full @babel parse would be the
 * ideal here; this stays string-based but no longer silently discards the
 * preamble.)
 */
function extractFnBody(tslCode: string, tslNames: string[]): ExtractedFn {
  const fnStart = tslCode.indexOf('Fn(() => {');
  let body = '';
  let head = '';
  if (fnStart !== -1) {
    const bodyOpen = fnStart + 'Fn(() => {'.length; // just past the `{`
    let depth = 1;
    let i = bodyOpen;
    while (i < tslCode.length && depth > 0) {
      const ch = tslCode[i];
      if (ch === '{') depth++;
      else if (ch === '}') depth--;
      i++;
    }
    if (depth === 0) {
      body = tslCode.slice(bodyOpen, i - 1).trim();
      // Start of the `const <name> = Fn(() => {` declaration line.
      const declStart = tslCode.lastIndexOf('\n', fnStart) + 1;
      head = tslCode.slice(0, declStart);
    }
  }

  const preambleImports: string[] = [];
  const preambleDecls: string[] = [];
  for (const rawLine of head.split('\n')) {
    if (/^\s*import\b/.test(rawLine)) {
      // three/tsl imports are regenerated by collectImports; keep any others.
      if (!/from\s*['"]three\/tsl['"]/.test(rawLine)) preambleImports.push(rawLine.trim());
    } else {
      preambleDecls.push(rawLine);
    }
  }
  // Trim leading/trailing blank decl lines so the re-emitted preamble is tidy.
  while (preambleDecls.length && !preambleDecls[0].trim()) preambleDecls.shift();
  while (preambleDecls.length && !preambleDecls[preambleDecls.length - 1].trim()) {
    preambleDecls.pop();
  }

  if (!body) {
    body = 'return vec3(1, 0, 0);';
    if (!tslNames.includes('vec3')) tslNames.push('vec3');
  }
  return { body, preambleImports, preambleDecls };
}

interface TDZResult {
  body: string;
  /**
   * Locals renamed because they shadowed an imported TSL name, mapped
   * original → renamed (e.g. a property named `mix` → `_mix`). buildShaderModule
   * reverses this so a renamed property uniform still resolves to a `params.<X>`
   * keyed by its *original* name (the name the live overlay & shaderloader
   * auto-detect from the un-rewritten generated code).
   */
  renames: Map<string, string>;
}

/**
 * Fix TDZ (Temporal Dead Zone) issues in generated code:
 * 1. Remove self-referencing bare declarations (const X = X;)
 * 2. Rename local variables that shadow imported function names
 * 3. Fix bare numeric first-arg in MaterialX noise calls
 */
function fixTDZ(body: string, tslNames: string[]): TDZResult {
  let processedBody = body;
  const importedNames = new Set(tslNames);
  const renames = new Map<string, string>();

  // 1. Remove self-referencing bare declarations: const X = X;
  for (const name of importedNames) {
    const selfRefRe = new RegExp(
      `^[ \\t]*const\\s+${name}\\s*=\\s*${name}\\s*;[ \\t]*$`, 'gm'
    );
    processedBody = processedBody.replace(selfRefRe, '');
  }

  // 2. Rename local variables that shadow imported function names
  const declRe = /\bconst\s+(\w+)\s*=/g;
  const conflicting = new Set<string>();
  let dm: RegExpExecArray | null;
  while ((dm = declRe.exec(processedBody)) !== null) {
    if (importedNames.has(dm[1])) {
      conflicting.add(dm[1]);
    }
  }
  for (const name of conflicting) {
    processedBody = processedBody.replace(
      new RegExp(`\\b${name}\\b(?!\\s*[:(])`, 'g'),
      `_${name}`,
    );
    renames.set(name, `_${name}`);
  }

  // 3. Fix bare numeric first-arg in MaterialX noise calls — default to uv()
  processedBody = processedBody.replace(
    /\b(mx_\w+)\(\s*0\s*\)/g,
    '$1(uv())',
  );
  processedBody = processedBody.replace(
    /\b(mx_\w+)\(\s*0\s*,/g,
    '$1(uv(),',
  );
  if (processedBody.includes('uv(') && !tslNames.includes('uv')) {
    tslNames.push('uv');
  }

  return { body: processedBody, renames };
}

/**
 * Pull `Discard(cond);` statements out of a body, returning the extracted
 * conditions and the remaining text. Uses paren-balancing (not an end-anchored
 * regex) so a discard with nested parens, a trailing `// comment`, or one split
 * across lines is handled rather than silently dropped. A genuinely unbalanced
 * `Discard(` is left in place (loud syntax error) instead of vanishing.
 */
function extractDiscards(bodyText: string): { conds: string[]; rest: string } {
  const conds: string[] = [];
  let rest = '';
  let lastCopied = 0;
  const re = /\bDiscard\s*\(/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(bodyText)) !== null) {
    // Don't treat a member call like `foo.Discard(` as the TSL Discard.
    if (m.index > 0 && bodyText[m.index - 1] === '.') continue;
    const argStart = m.index + m[0].length; // just past the `(`
    let depth = 1;
    let j = argStart;
    for (; j < bodyText.length && depth > 0; j++) {
      const ch = bodyText[j];
      if (ch === '(') depth++;
      else if (ch === ')') depth--;
    }
    if (depth !== 0) break; // unbalanced — leave the remainder untouched
    const argEnd = j - 1; // index of the matching `)`
    conds.push(bodyText.slice(argStart, argEnd).trim());

    rest += bodyText.slice(lastCopied, m.index);
    let k = argEnd + 1;
    while (k < bodyText.length && /[ \t]/.test(bodyText[k])) k++;
    if (bodyText[k] === ';') k++;
    // Swallow the remainder of the line only if it's whitespace / a line comment;
    // keep any real trailing statement.
    let tailStart = k;
    while (k < bodyText.length && bodyText[k] !== '\n') k++;
    if (/^\s*(\/\/.*)?$/.test(bodyText.slice(tailStart, k))) {
      if (bodyText[k] === '\n') k++;
    } else {
      k = tailStart;
    }
    lastCopied = k;
    re.lastIndex = k;
  }
  rest += bodyText.slice(lastCopied);
  return { conds, rest };
}

/** Parse processed body into definition lines and output channels. */
function parseBody(
  processedBody: string,
  tslNames: string[],
): ProcessedBody {
  const defLines: string[] = [];
  const channels: Record<string, string> = {};

  for (const rawLine of processedBody.split('\n')) {
    const trimmed = rawLine.trim();
    if (!trimmed) continue;

    const objReturn = trimmed.match(/^return\s*\{(.+)\}\s*;?$/);
    const simpleReturn = trimmed.match(/^return\s+(.+);$/);

    if (objReturn) {
      for (const prop of objReturn[1].split(',')) {
        const colonIdx = prop.indexOf(':');
        if (colonIdx !== -1) {
          const key = prop.slice(0, colonIdx).trim();
          const val = prop.slice(colonIdx + 1).trim();
          if (key && val) channels[key] = val;
        }
      }
    } else if (simpleReturn) {
      channels['color'] = simpleReturn[1].trim();
    } else {
      defLines.push(rawLine);
    }
  }

  if (Object.keys(channels).length === 0) {
    channels['color'] = 'vec3(1, 0, 0)';
    if (!tslNames.includes('vec3')) tslNames.push('vec3');
  }

  return { defLines, channels };
}

/** THREE.FrontSide=0, THREE.BackSide=1, THREE.DoubleSide=2 */
const SIDE_VALUES: Record<string, number> = {
  front: 0,
  back: 1,
  double: 2,
};

interface ShaderModuleProperty {
  name: string;
  defaultValue: number;
}

export interface BuildShaderModuleOptions {
  materialSettings?: MaterialSettings;
  /**
   * Comment lines emitted above the import statements. The standalone `.js`
   * export uses this for its usage header; the live preview omits it.
   */
  header?: string[];
  /**
   * Declared float properties. When provided (export), only `uniform(V)`
   * declarations whose (sanitized) name matches a declared property are rewritten
   * to `params.<name>`; unwired properties are still declared in the schema using
   * their `defaultValue`. When omitted (preview), every `uniform(V)` declaration
   * is auto-detected. In BOTH modes a wired uniform's schema default comes from
   * its code literal `V`, so the exported file matches the preview byte-for-byte.
   */
  properties?: ShaderModuleProperty[];
}

/**
 * Convert Fn-wrapped editor TSL into a shaderloader-compatible ES module. This
 * is the SINGLE source of truth shared by the live preview (tslToPreviewHTML)
 * and the `.js` export (tslToShaderModule) — they must never diverge, because
 * any divergence means the export ships a shader that differs from what the
 * user previewed.
 *
 * The shaderloader calls the default export as a *plain function* (no active
 * TSL stack) and assigns `material.colorNode = result.colorNode` directly, so
 * two rules are non-negotiable and historically easy to break with ad-hoc
 * per-line string surgery (which is exactly what produced the struct-as-
 * colorNode export bug):
 *
 *   1. Object returns (`{ color, position, ... }`) MUST be parsed per channel.
 *      `parseBody` matches the object-form return before the bare-value form so
 *      a `{ ... }` literal is never swallowed whole into a single color slot —
 *      assigning a struct to `colorNode` makes the renderer read uninitialised
 *      memory (random color each reload) and drops every other channel.
 *   2. `Discard()` needs an active stack, so the color channel is routed
 *      through a tiny `__pixel` Fn. Its discard conditions and color node are
 *      passed as explicit Fn *parameters*, never closure-captured: Three.js
 *      r173 (where first diagnosed; the bundled A-Frame build is now r184) did not propagate closure-captured
 *      derived nodes into an Fn body invoked from an outer plain function,
 *      which would otherwise resolve the color to a default (solid red).
 */
export function buildShaderModule(
  tslCode: string,
  options: BuildShaderModuleOptions = {},
): string {
  const { materialSettings, header, properties } = options;

  const { tslNames } = collectImports(tslCode, true);
  const { body, preambleImports, preambleDecls } = extractFnBody(tslCode, tslNames);
  const { body: processedBody, renames } = fixTDZ(body, tslNames);
  const { defLines, channels } = parseBody(processedBody, tslNames);

  // Module-scope helper Fns (hsl/toHsl) live in the preamble and need `Fn`.
  if (/\bFn\s*\(/.test(preambleDecls.join('\n')) && !tslNames.includes('Fn')) {
    tslNames.push('Fn');
  }

  // Ensure positionLocal (and normalLocal for normal-based displacement) are available.
  const displacementMode = materialSettings?.displacementMode ?? 'normal';
  if (channels.position) {
    if (!tslNames.includes('positionLocal')) tslNames.push('positionLocal');
    if (displacementMode === 'normal' && !tslNames.includes('normalLocal')) {
      tslNames.push('normalLocal');
    }
  }

  // --- Property uniforms → params + schema --------------------------------
  //
  // Rewriting `const X = uniform(N)` to `const X = params.X` (plus an explicit
  // `schema`) makes the shaderloader create the uniforms up-front and pass them
  // in, so the live overlay's `_propertyUniforms.X.value = …` reaches the
  // material instead of mutating a throwaway anonymous uniform.
  //
  // EVERY `uniform()` line is keyed off its ACTUAL generated var name (only
  // property_float emits uniform(), and the shaderloader auto-detects every
  // `const X = uniform(V)` as a property at runtime regardless). Keying off the
  // real var — not a name recomputed from the property list — is what keeps two
  // properties whose names sanitize to the same base (`my speed`, `my-speed` →
  // graphToCode emits `my_speed`, `my_speed2`) BOTH exposed instead of one
  // silently overwriting the other.
  //
  // The schema key is the *pre-fixTDZ* var name (`reverseRename`) — the name the
  // live overlay & shaderloader auto-detect from the un-rewritten code — so a
  // property whose name collides with a TSL import (renamed `mix` → `_mix`)
  // still resolves to `params.mix`.
  const reverseRename = new Map<string, string>();
  for (const [orig, renamed] of renames) reverseRename.set(renamed, orig);

  const explicit = !!(properties && properties.length > 0);
  const schemaEntries: Record<string, number> = {};
  // Export declares all properties up-front so the a-entity API documents them
  // even when a property node isn't wired (no `uniform()` line). Wired ones get
  // their default overwritten below from the code literal, keeping the schema
  // default identical to the preview's auto-detected value (#9 parity). Schema
  // keys are sanitized to match graphToCode's generated var names.
  if (explicit) {
    for (const p of properties!) schemaEntries[sanitizeIdentifier(p.name)] = p.defaultValue;
  }
  // Accept any numeric literal — including scientific notation (`1e-7`) and
  // leading-dot (`.5`), both of which `String(value)` can produce — so a
  // property at an extreme value isn't left as an undriveable literal uniform.
  const uniformLineRe =
    /^(\s*)const\s+(\w+)\s*=\s*uniform\(\s*([-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)\s*\)\s*;?\s*$/;
  const rewrittenDefLines = defLines.map((line) => {
    const m = line.match(uniformLineRe);
    if (!m) return line;
    const [, indent, codeVar, rawVal] = m;
    const schemaKey = reverseRename.get(codeVar) ?? codeVar;
    const v = parseFloat(rawVal);
    schemaEntries[schemaKey] = isNaN(v) ? 0 : v;
    return `${indent}const ${codeVar} = params.${schemaKey};`;
  });
  const hasParams = Object.keys(schemaEntries).length > 0;

  // --- Pull Discard(...) out for the __pixel wrapper ----------------------
  const { conds: discardConds, rest: nonDiscardText } = extractDiscards(
    rewrittenDefLines.join('\n'),
  );
  const nonDiscardLines = nonDiscardText.split('\n').filter((l) => l.trim());
  const hasDiscard = discardConds.length > 0;
  if (hasDiscard && !tslNames.includes('Fn')) tslNames.push('Fn');

  // Default color carrying a discard when no color channel is wired: white is
  // the MeshStandard base color, so the cutout applies without changing the
  // look of the surviving fragments.
  const discardColor = channels.color ?? 'vec3(1, 1, 1)';
  if (hasDiscard && !channels.color && !tslNames.includes('vec3')) tslNames.push('vec3');
  const pixelCallArgs = hasDiscard ? [...discardConds, discardColor] : [];

  // --- Build the return object (node property names per channel) ----------
  const returnProps: string[] = [];
  let colorEmitted = false;
  for (const [ch, ref] of Object.entries(channels)) {
    const prop = CHANNEL_TO_PROP[ch];
    if (!prop) continue;
    if (ch === 'position') {
      const displacement = displacementMode === 'normal'
        ? `normalLocal.mul(${ref})`
        : ref;
      returnProps.push(`${prop}: positionLocal.add(${displacement})`);
    } else if (ch === 'color' && hasDiscard) {
      returnProps.push(`${prop}: __pixel(${pixelCallArgs.join(', ')})`);
      colorEmitted = true;
    } else {
      returnProps.push(`${prop}: ${ref}`);
      if (ch === 'color') colorEmitted = true;
    }
  }
  // A discard only runs inside the __pixel Fn routed through colorNode. If the
  // graph wired a discard but no color (e.g. discard + position), still emit the
  // color channel so the cutout isn't silently dropped with a dead __pixel.
  if (hasDiscard && !colorEmitted) {
    returnProps.unshift(`${CHANNEL_TO_PROP.color}: __pixel(${pixelCallArgs.join(', ')})`);
  }

  if (materialSettings?.transparent) returnProps.push('transparent: true');
  if (materialSettings?.side) {
    returnProps.push(`side: ${SIDE_VALUES[materialSettings.side] ?? 0}`);
  }
  if (materialSettings?.alphaTest) {
    returnProps.push(`alphaTest: ${materialSettings.alphaTest}`);
  }

  // --- The __pixel Fn: conditions + color as explicit params (see rule 2) -
  const pixelFnLines: string[] = [];
  if (hasDiscard) {
    const fnParams = [...discardConds.map((_, i) => `__c${i}`), '__color'];
    pixelFnLines.push(`  const __pixel = Fn(([${fnParams.join(', ')}]) => {`);
    discardConds.forEach((_, i) => pixelFnLines.push(`    Discard(__c${i});`));
    pixelFnLines.push('    return __color;');
    pixelFnLines.push('  });');
  }

  // --- Explicit schema export so original defaults survive ----------------
  const schemaLines: string[] = [];
  if (hasParams) {
    schemaLines.push('export const schema = {');
    for (const [name, def] of Object.entries(schemaEntries)) {
      schemaLines.push(`  ${name}: { type: 'number', default: ${def} },`);
    }
    schemaLines.push('};');
    schemaLines.push('');
  }

  const imports: string[] = [...preambleImports];
  if (tslNames.length > 0) {
    imports.push(`import { ${tslNames.join(', ')} } from 'three/tsl';`);
  }

  const lines = [
    ...(header && header.length ? [...header, ''] : []),
    ...imports,
    '',
    ...schemaLines,
    ...(preambleDecls.length ? [...preambleDecls, ''] : []),
    `export default function(${hasParams ? 'params' : ''}) {`,
    ...nonDiscardLines.map((l) => '  ' + l.trimStart()),
    ...pixelFnLines,
    `  return { ${returnProps.join(', ')} };`,
    '}',
  ];

  return lines.join('\n') + '\n';
}
