import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'fs';
import path from 'path';

/**
 * The shared A-Frame preview scripts have a SINGLE source of truth in the
 * `a-frame-shaderloader/` submodule's `js/` dir. The vite `fs-vendor-sync`
 * plugin copies them into the app (`public/js`) and the ShaderCarousel bench
 * (`ShaderCarousel/components/three`) at dev/build start.
 *
 * This suite fails on DRIFT — a consumer copy that differs from the source
 * (e.g. someone hand-edits `public/js/a-frame-shaderloader-0.6.js` instead of
 * the submodule source). Fix drift by editing the submodule source and
 * re-running `vite` (dev or build), never by editing a copy.
 *
 * The A-Frame IIFE bundle is an untracked build artifact (emitted by
 * `build/build.mjs`, regenerated by the sync plugin), so on a fresh clone /
 * CI run that hasn't built yet the SOURCE may be absent. In that case the
 * comparison is skipped (nothing to verify) rather than failed — but if the
 * source EXISTS and a copy is missing or differs, that's real drift and fails.
 */
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'a-frame-shaderloader/js');

const COPIES: Record<string, string[]> = {
  'a-frame-180-a-01.min.js': ['public/js', 'ShaderCarousel/components/three'],
  'a-frame-shaderloader-0.6.js': ['public/js'],
  'aframe-orbit-controls.min.js': ['public/js'],
};

describe('vendored A-Frame scripts stay in sync with the submodule source', () => {
  for (const [file, dests] of Object.entries(COPIES)) {
    const srcPath = path.join(SRC, file);
    const srcMissing = !existsSync(srcPath);
    for (const dest of dests) {
      // Skip only when the canonical source artifact isn't present in this
      // environment (e.g. unbuilt fresh clone). A missing copy WITH a present
      // source is genuine drift and must fail below.
      it.skipIf(srcMissing)(
        `${dest}/${file} is byte-identical to a-frame-shaderloader/js/${file}`,
        () => {
          const dstPath = path.join(ROOT, dest, file);
          expect(existsSync(dstPath), `copy missing — sync did not run: ${dstPath}`).toBe(true);
          expect(
            readFileSync(dstPath).equals(readFileSync(srcPath)),
            `drift: ${dest}/${file} differs from the submodule source — edit the source, not the copy`,
          ).toBe(true);
        },
      );
    }
  }

  /**
   * COPIES is an ALLOW-LIST, which is the one way this guard rots silently: a
   * script added to the submodule and never listed here is simply not checked,
   * so it can drift from its vendored copy forever while the suite stays green.
   * (Measured risk, not hypothetical — 0.6 was added to the submodule and to
   * vite's sync targets in the same change as this assertion.) Scanning the
   * source directory turns "forgot to add a row" into a failure instead.
   */
  // Scripts the submodule ships that this app deliberately does NOT vendor.
  // Deliberate-only, and checked for staleness below, so an entry can never
  // quietly excuse a future file.
  const NOT_VENDORED: Record<string, string> = {
    'tsl-textures.min.js':
      'dropped when the noise family moved to three\'s built-in MaterialX ' +
      'functions; the submodule still ships it for its own demos.',
    // 51 KB of dist (17 KB gzipped) that nothing could ever load. Verified by
    // grep: same-origin loader resolution happens only in tslToPreviewHTML
    // (LOADER_FILE = 0.6) and podest.html (0.6 hardcoded, twice). Shaders
    // exported against 0.4/0.5 reference them on jsdelivr BY URL — i.e. from
    // the SUBMODULE, which is why they must stay frozen there and why dropping
    // the copies cannot break a single already-exported shader.
    'a-frame-shaderloader-0.4.js':
      'frozen for shaders exported before 0.5; they load it from the CDN, ' +
      'never from this app, so the vendored copy had no consumer.',
    'a-frame-shaderloader-0.5.js':
      'frozen for shaders exported before 0.6; same as 0.4 — CDN-only. ' +
      'Tests/index.html loads it from the submodule path, not public/js.',
  };

  it('lists every script the submodule ships — no unpoliced vendored file', () => {
    if (!existsSync(SRC)) return; // fresh clone without the submodule checked out
    const shipped = readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
    const accounted = new Set([...Object.keys(COPIES), ...Object.keys(NOT_VENDORED)]);
    expect(
      shipped.filter((f) => !accounted.has(f)),
      'vendored script missing from COPIES — add it (and to VENDOR_TARGETS in ' +
        'vite.config.ts), or add it to NOT_VENDORED with the reason',
    ).toEqual([]);
  });

  /**
   * The other direction. The two assertions around this one both read the
   * SUBMODULE, so nothing noticed if a deliberately-dropped script reappeared
   * in public/js — and the sync plugin only ever copies, never prunes, so it
   * would ship silently. MEASURED: putting 0.4 + 0.5 back left the whole suite
   * green while adding 51 KB to dist/js.
   */
  it('does not re-vendor a deliberately dropped script', () => {
    const backAgain = Object.keys(NOT_VENDORED).filter((f) =>
      existsSync(path.join(ROOT, 'public/js', f)));
    expect(
      backAgain,
      'a NOT_VENDORED script is back in public/js — it was dropped on purpose. ' +
        'Delete the copy, or move it to COPIES + VENDOR_TARGETS if it really ' +
        'has a same-origin consumer again.',
    ).toEqual([]);
  });

  it('carries no stale not-vendored exemption', () => {
    if (!existsSync(SRC)) return;
    const shipped = new Set(readdirSync(SRC));
    expect(
      Object.keys(NOT_VENDORED).filter((f) => !shipped.has(f)),
      'exemption for a file the submodule no longer ships — delete the entry',
    ).toEqual([]);
  });
});

/**
 * The ShaderCarousel bench pages resolve `three` through their own
 * `<script type="importmap">`. That works on every host that serves the suite
 * as static files, but NOT under `vite dev`, which rewrites bare specifiers to
 * its pre-bundled deps and ignores import maps — `three` then resolved to the
 * app's PLAIN three build, whose module has no `WebGPURenderer` export, and
 * `bench-driver.js` died with a SyntaxError before registering anything (the
 * "Benchmark this device" button did nothing, with the cause console-only).
 *
 * `vite.config.ts`'s dev-only `fs-carousel-importmap-dev` plugin fixes that by
 * READING these maps and resolving carousel imports the same way. One resolver
 * serves both pages, so the two maps must agree — and every target must exist,
 * since a dev-server resolution that points at a missing file fails as an
 * opaque 404 mid-module-graph.
 */
describe('ShaderCarousel import maps (the dev resolver reads these)', () => {
  const PAGES = ['bench-microplane', 'bench-static'];
  const mapOf = (dir: string) => {
    const page = path.resolve(process.cwd(), 'ShaderCarousel', dir, 'index.html');
    const block = readFileSync(page, 'utf-8')
      .match(/<script\s+type=["']importmap["']\s*>([\s\S]*?)<\/script>/i);
    expect(block, `${dir}/index.html has no import map`).not.toBeNull();
    return { page, imports: JSON.parse(block![1]).imports as Record<string, string> };
  };

  it('both bench pages declare the SAME map, and every target exists', () => {
    const maps = PAGES.map(mapOf);
    for (const { page, imports } of maps) {
      expect(Object.keys(imports).length, page).toBeGreaterThan(0);
      for (const [spec, rel] of Object.entries(imports)) {
        const target = path.resolve(path.dirname(page), rel);
        expect(existsSync(target), `${page}: "${spec}" → missing ${rel}`).toBe(true);
      }
    }
    // Resolved to absolute paths: the two pages sit at the same depth, so
    // identical relative values must land on identical files.
    const resolved = maps.map(({ page, imports }) =>
      Object.fromEntries(Object.entries(imports)
        .map(([k, v]) => [k, path.resolve(path.dirname(page), v)])));
    expect(resolved[1], 'the two bench pages must resolve `three` identically').toEqual(resolved[0]);
  });

  it('`three` resolves to the WEBGPU build — the plain one has no WebGPURenderer', () => {
    // The exact confusion the dev-server bug produced: a build that parses but
    // lacks the export the driver imports.
    for (const dir of PAGES) {
      const { imports } = mapOf(dir);
      expect(imports.three, dir).toMatch(/three\.webgpu(\.min)?\.js$/);
    }
    const webgpu = path.resolve(process.cwd(), 'ShaderCarousel/lib/three/three.webgpu.min.js');
    expect(readFileSync(webgpu, 'utf-8')).toContain('WebGPURenderer');
  });
});

/**
 * The SAME drift class, for the other vendored family — and the one the
 * assertions above do NOT cover. `ShaderCarousel/lib/three/*.min.js` are hand
 * copies of `node_modules/three/build/`, made once (Jul 2026) with no plugin
 * and no guard: `fs-vendor-sync` copies only the A-Frame family, so nothing
 * re-copies these and nothing noticed if they fell behind.
 *
 * Why that matters more than a stale demo asset would: the carousel benches are
 * the instrument that PRICES nodes — their exports become `complexity.json` —
 * so a renderer-version split between the app and its own calibration
 * instrument would invalidate the cost table with a fully green suite. And
 * `package.json` pins `three` with a CARET (`^0.184.0`), so a routine
 * `npm update` moves the app forward and leaves these three files behind
 * without touching a single tracked byte.
 *
 * Skipped when `node_modules/three` is absent (the `srcMissing` pattern above):
 * nothing to compare against, not a failure.
 */
describe('ShaderCarousel three build stays in sync with node_modules/three', () => {
  const THREE_BUILD = path.join(ROOT, 'node_modules/three/build');
  const CAROUSEL_THREE = path.join(ROOT, 'ShaderCarousel/lib/three');
  const FILES = ['three.core.min.js', 'three.tsl.min.js', 'three.webgpu.min.js'];
  const buildMissing = !existsSync(THREE_BUILD);

  for (const file of FILES) {
    it.skipIf(buildMissing)(
      `ShaderCarousel/lib/three/${file} is byte-identical to node_modules/three/build/${file}`,
      () => {
        const copy = path.join(CAROUSEL_THREE, file);
        const src = path.join(THREE_BUILD, file);
        expect(existsSync(copy), `carousel copy missing: ${copy}`).toBe(true);
        expect(existsSync(src), `three no longer ships ${file} — re-check the copy list`).toBe(true);
        expect(
          readFileSync(copy).equals(readFileSync(src)),
          `drift: ShaderCarousel/lib/three/${file} is not the installed three build. ` +
            'Re-copy it from node_modules/three/build (the benches must run the ' +
            'SAME renderer the app does, or the points they measure price a ' +
            'different runtime than the one the cost bar reports).',
        ).toBe(true);
      },
    );
  }
});
