import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import path from 'path';

/**
 * The shared A-Frame preview scripts have a SINGLE source of truth in the
 * `a-frame-shaderloader/` submodule's `js/` dir. The vite `fs-vendor-sync`
 * plugin copies them into the app (`public/js`) and the ShaderCarousel bench
 * (`ShaderCarousel/components/three`) at dev/build start.
 *
 * This suite fails on DRIFT — a consumer copy that differs from the source
 * (e.g. someone hand-edits `public/js/a-frame-shaderloader-0.4.js` instead of
 * the submodule source). Fix drift by editing the submodule source and
 * re-running `vite` (dev or build), never by editing a copy.
 *
 * The A-Frame IIFE bundle is an untracked build artifact (emitted by
 * `build/build.mjs`, regenerated by the sync plugin), so on a fresh clone /
 * CI run that hasn't built yet the SOURCE may be absent. In that case the
 * comparison is skipped (nothing to verify) rather than failed — but if the
 * source EXISTS and a copy is missing or differs, that's real drift and fails.
 */
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'a-frame-shaderloader/js');

const COPIES: Record<string, string[]> = {
  'a-frame-180-a-01.min.js': ['public/js', 'ShaderCarousel/components/three'],
  'a-frame-shaderloader-0.4.js': ['public/js'],
  'a-frame-shaderloader-0.5.js': ['public/js'],
  'aframe-orbit-controls.min.js': ['public/js'],
};

describe('vendored A-Frame scripts stay in sync with the submodule source', () => {
  for (const [file, dests] of Object.entries(COPIES)) {
    const srcPath = path.join(SRC, file);
    const srcMissing = !existsSync(srcPath);
    for (const dest of dests) {
      // Skip only when the canonical source artifact isn't present in this
      // environment (e.g. unbuilt fresh clone). A missing copy WITH a present
      // source is genuine drift and must fail below.
      it.skipIf(srcMissing)(
        `${dest}/${file} is byte-identical to a-frame-shaderloader/js/${file}`,
        () => {
          const dstPath = path.join(ROOT, dest, file);
          expect(existsSync(dstPath), `copy missing — sync did not run: ${dstPath}`).toBe(true);
          expect(
            readFileSync(dstPath).equals(readFileSync(srcPath)),
            `drift: ${dest}/${file} differs from the submodule source — edit the source, not the copy`,
          ).toBe(true);
        },
      );
    }
  }
});

/**
 * The ShaderCarousel bench pages resolve `three` through their own
 * `<script type="importmap">`. That works on every host that serves the suite
 * as static files, but NOT under `vite dev`, which rewrites bare specifiers to
 * its pre-bundled deps and ignores import maps — `three` then resolved to the
 * app's PLAIN three build, whose module has no `WebGPURenderer` export, and
 * `bench-driver.js` died with a SyntaxError before registering anything (the
 * "Benchmark this device" button did nothing, with the cause console-only).
 *
 * `vite.config.ts`'s dev-only `fs-carousel-importmap-dev` plugin fixes that by
 * READING these maps and resolving carousel imports the same way. One resolver
 * serves both pages, so the two maps must agree — and every target must exist,
 * since a dev-server resolution that points at a missing file fails as an
 * opaque 404 mid-module-graph.
 */
describe('ShaderCarousel import maps (the dev resolver reads these)', () => {
  const PAGES = ['bench-microplane', 'bench-static'];
  const mapOf = (dir: string) => {
    const page = path.resolve(process.cwd(), 'ShaderCarousel', dir, 'index.html');
    const block = readFileSync(page, 'utf-8')
      .match(/<script\s+type=["']importmap["']\s*>([\s\S]*?)<\/script>/i);
    expect(block, `${dir}/index.html has no import map`).not.toBeNull();
    return { page, imports: JSON.parse(block![1]).imports as Record<string, string> };
  };

  it('both bench pages declare the SAME map, and every target exists', () => {
    const maps = PAGES.map(mapOf);
    for (const { page, imports } of maps) {
      expect(Object.keys(imports).length, page).toBeGreaterThan(0);
      for (const [spec, rel] of Object.entries(imports)) {
        const target = path.resolve(path.dirname(page), rel);
        expect(existsSync(target), `${page}: "${spec}" → missing ${rel}`).toBe(true);
      }
    }
    // Resolved to absolute paths: the two pages sit at the same depth, so
    // identical relative values must land on identical files.
    const resolved = maps.map(({ page, imports }) =>
      Object.fromEntries(Object.entries(imports)
        .map(([k, v]) => [k, path.resolve(path.dirname(page), v)])));
    expect(resolved[1], 'the two bench pages must resolve `three` identically').toEqual(resolved[0]);
  });

  it('`three` resolves to the WEBGPU build — the plain one has no WebGPURenderer', () => {
    // The exact confusion the dev-server bug produced: a build that parses but
    // lacks the export the driver imports.
    for (const dir of PAGES) {
      const { imports } = mapOf(dir);
      expect(imports.three, dir).toMatch(/three\.webgpu(\.min)?\.js$/);
    }
    const webgpu = path.resolve(process.cwd(), 'ShaderCarousel/lib/three/three.webgpu.min.js');
    expect(readFileSync(webgpu, 'utf-8')).toContain('WebGPURenderer');
  });
});
