import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'fs';
import path from 'path';
import { createHash } from 'crypto';

/**
 * The shared A-Frame preview scripts have a SINGLE source of truth in the
 * `a-frame-shaderloader/` submodule's `js/` dir. The vite `fs-vendor-sync`
 * plugin copies them into the app (`public/js`) and the ShaderCarousel bench
 * (`ShaderCarousel/components/three`) at dev/build start.
 *
 * This suite fails on DRIFT — a consumer copy that differs from the source
 * (e.g. someone hand-edits `public/js/a-frame-shaderloader-0.8.js` instead of
 * the submodule source). Fix drift by editing the submodule source and
 * re-running `vite` (dev or build), never by editing a copy.
 *
 * The A-Frame IIFE bundle is an untracked build artifact (emitted by
 * `build/build.mjs`, regenerated by the sync plugin), so on a fresh clone /
 * CI run that hasn't built yet the SOURCE may be absent. In that case the
 * comparison is skipped (nothing to verify) rather than failed — but if the
 * source EXISTS and a copy is missing or differs, that's real drift and fails.
 */
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'a-frame-shaderloader/js');

const COPIES: Record<string, string[]> = {
  'a-frame-180-a-01.min.js': ['public/js', 'ShaderCarousel/components/three'],
  // The loader every surface loads (src/shaderloaderHarness.ts reads this
  // served copy; the check below is what keeps it the submodule's bytes).
  'a-frame-shaderloader-0.8.js': ['public/js'],
  'aframe-orbit-controls.min.js': ['public/js'],
  // The glTF decoders (Draco + meshopt for meshes, the Basis Universal
  // transcoder for KTX2 textures) and the README carrying their licences. Their
  // SOURCE is three itself — see the node_modules/three describe at the end of
  // this file.
  'decoders/draco_wasm_wrapper.js': ['public/js'],
  'decoders/draco_decoder.wasm': ['public/js'],
  'decoders/meshopt_decoder.module.js': ['public/js'],
  'decoders/basis_transcoder.js': ['public/js'],
  'decoders/basis_transcoder.wasm': ['public/js'],
  'decoders/README.md': ['public/js'],
};

describe('vendored A-Frame scripts stay in sync with the submodule source', () => {
  for (const [file, dests] of Object.entries(COPIES)) {
    const srcPath = path.join(SRC, file);
    const srcMissing = !existsSync(srcPath);
    for (const dest of dests) {
      // Skip only when the canonical source artifact isn't present in this
      // environment (e.g. unbuilt fresh clone). A missing copy WITH a present
      // source is genuine drift and must fail below.
      it.skipIf(srcMissing)(
        `${dest}/${file} is byte-identical to a-frame-shaderloader/js/${file}`,
        () => {
          const dstPath = path.join(ROOT, dest, file);
          expect(existsSync(dstPath), `copy missing — sync did not run: ${dstPath}`).toBe(true);
          expect(
            readFileSync(dstPath).equals(readFileSync(srcPath)),
            `drift: ${dest}/${file} differs from the submodule source — edit the source, not the copy`,
          ).toBe(true);
        },
      );
    }
  }

  /**
   * COPIES is an ALLOW-LIST, which is the one way this guard rots silently: a
   * script added to the submodule and never listed here is simply not checked,
   * so it can drift from its vendored copy forever while the suite stays green.
   * (Measured risk, not hypothetical — 0.6 was added to the submodule and to
   * vite's sync targets in the same change as this assertion.) Scanning the
   * source directory turns "forgot to add a row" into a failure instead.
   */
  // Scripts the submodule ships that this app deliberately does NOT vendor.
  // Deliberate-only, and checked for staleness below, so an entry can never
  // quietly excuse a future file.
  const NOT_VENDORED: Record<string, string> = {
    'tsl-textures.min.js':
      'dropped when the noise family moved to three\'s built-in MaterialX ' +
      'functions; the submodule still ships it for its own demos.',
    // 51 KB of dist (17 KB gzipped) that nothing could ever load. Verified by
    // grep: same-origin loader resolution happens only in tslToPreviewHTML
    // (LOADER_FILE = 0.8) and podest.html (0.8 hardcoded, twice, pinned to
    // LOADER_FILE by perMeshMaterials.test.ts). Shaders exported against
    // 0.4/0.5/0.6 reference them on jsdelivr BY URL — i.e. from the SUBMODULE,
    // which is why they must stay frozen there (frozenLoaders.test.ts pins
    // their hashes) and why dropping the copies cannot break a single
    // already-exported shader.
    'a-frame-shaderloader-0.4.js':
      'frozen for shaders exported before 0.5; they load it from the CDN, ' +
      'never from this app, so the vendored copy had no consumer.',
    'a-frame-shaderloader-0.5.js':
      'frozen for shaders exported before 0.6; same as 0.4 — CDN-only. ' +
      'Tests/index.html loads it from the submodule path, not public/js.',
    'a-frame-shaderloader-0.6.js':
      'frozen for shaders exported before 0.8; they load it from the CDN. ' +
      'Every same-origin consumer (preview, XR popup, podest stage and VR ' +
      'popup) moved to 0.8, so the copy has no consumer.',
  };

  it('lists every script the submodule ships — no unpoliced vendored file', () => {
    if (!existsSync(SRC)) return; // fresh clone without the submodule checked out
    // decoders/ is counted WHOLE, not just its *.js: a .wasm or a README added
    // there ships to public/js too, so it must be policed like a script.
    const decodersDir = path.join(SRC, 'decoders');
    const decoderFiles = existsSync(decodersDir)
      ? readdirSync(decodersDir).map((f) => `decoders/${f}`)
      : [];
    const shipped = [...readdirSync(SRC).filter((f) => f.endsWith('.js')), ...decoderFiles].sort();
    const accounted = new Set([...Object.keys(COPIES), ...Object.keys(NOT_VENDORED)]);
    expect(
      shipped.filter((f) => !accounted.has(f)),
      'vendored script missing from COPIES — add it (and to VENDOR_TARGETS in ' +
        'vite.config.ts), or add it to NOT_VENDORED with the reason',
    ).toEqual([]);
  });

  /**
   * The other direction. The two assertions around this one both read the
   * SUBMODULE, so nothing noticed if a deliberately-dropped script reappeared
   * in public/js — and the sync plugin only ever copies, never prunes, so it
   * would ship silently. MEASURED: putting 0.4 + 0.5 back left the whole suite
   * green while adding 51 KB to dist/js.
   */
  it('does not re-vendor a deliberately dropped script', () => {
    const backAgain = Object.keys(NOT_VENDORED).filter((f) =>
      existsSync(path.join(ROOT, 'public/js', f)));
    expect(
      backAgain,
      'a NOT_VENDORED script is back in public/js — it was dropped on purpose. ' +
        'Delete the copy, or move it to COPIES + VENDOR_TARGETS if it really ' +
        'has a same-origin consumer again.',
    ).toEqual([]);
  });

  it('carries no stale not-vendored exemption', () => {
    if (!existsSync(SRC)) return;
    const shipped = new Set(readdirSync(SRC));
    expect(
      Object.keys(NOT_VENDORED).filter((f) => !shipped.has(f)),
      'exemption for a file the submodule no longer ships — delete the entry',
    ).toEqual([]);
  });
});

/**
 * The ShaderCarousel bench pages resolve `three` through their own
 * `<script type="importmap">`. That works on every host that serves the suite
 * as static files, but NOT under `vite dev`, which rewrites bare specifiers to
 * its pre-bundled deps and ignores import maps — `three` then resolved to the
 * app's PLAIN three build, whose module has no `WebGPURenderer` export, and
 * `bench-driver.js` died with a SyntaxError before registering anything (the
 * "Benchmark this device" button did nothing, with the cause console-only).
 *
 * `vite.config.ts`'s dev-only `fs-carousel-importmap-dev` plugin fixes that by
 * READING these maps and resolving carousel imports the same way. One resolver
 * serves both pages, so the two maps must agree — and every target must exist,
 * since a dev-server resolution that points at a missing file fails as an
 * opaque 404 mid-module-graph.
 */
describe('ShaderCarousel import maps (the dev resolver reads these)', () => {
  const PAGES = ['bench-microplane', 'bench-static'];
  const mapOf = (dir: string) => {
    const page = path.resolve(process.cwd(), 'ShaderCarousel', dir, 'index.html');
    const block = readFileSync(page, 'utf-8')
      .match(/<script\s+type=["']importmap["']\s*>([\s\S]*?)<\/script>/i);
    expect(block, `${dir}/index.html has no import map`).not.toBeNull();
    return { page, imports: JSON.parse(block![1]).imports as Record<string, string> };
  };

  it('both bench pages declare the SAME map, and every target exists', () => {
    const maps = PAGES.map(mapOf);
    for (const { page, imports } of maps) {
      expect(Object.keys(imports).length, page).toBeGreaterThan(0);
      for (const [spec, rel] of Object.entries(imports)) {
        const target = path.resolve(path.dirname(page), rel);
        expect(existsSync(target), `${page}: "${spec}" → missing ${rel}`).toBe(true);
      }
    }
    // Resolved to absolute paths: the two pages sit at the same depth, so
    // identical relative values must land on identical files.
    const resolved = maps.map(({ page, imports }) =>
      Object.fromEntries(Object.entries(imports)
        .map(([k, v]) => [k, path.resolve(path.dirname(page), v)])));
    expect(resolved[1], 'the two bench pages must resolve `three` identically').toEqual(resolved[0]);
  });

  it('`three` resolves to the WEBGPU build — the plain one has no WebGPURenderer', () => {
    // The exact confusion the dev-server bug produced: a build that parses but
    // lacks the export the driver imports.
    for (const dir of PAGES) {
      const { imports } = mapOf(dir);
      expect(imports.three, dir).toMatch(/three\.webgpu(\.min)?\.js$/);
    }
    const webgpu = path.resolve(process.cwd(), 'ShaderCarousel/lib/three/three.webgpu.min.js');
    expect(readFileSync(webgpu, 'utf-8')).toContain('WebGPURenderer');
  });
});

/**
 * The SAME drift class, for the other vendored family — and the one the
 * assertions above do NOT cover. `ShaderCarousel/lib/three/*.min.js` are hand
 * copies of `node_modules/three/build/`, made once (Jul 2026) with no plugin
 * and no guard: `fs-vendor-sync` copies only the A-Frame family, so nothing
 * re-copies these and nothing noticed if they fell behind.
 *
 * Why that matters more than a stale demo asset would: the carousel benches are
 * the instrument that PRICES nodes — their exports become `complexity.json` —
 * so a renderer-version split between the app and its own calibration
 * instrument would invalidate the cost table with a fully green suite. And
 * `package.json` pins `three` with a CARET (`^0.184.0`), so a routine
 * `npm update` moves the app forward and leaves these three files behind
 * without touching a single tracked byte.
 *
 * Skipped when `node_modules/three` is absent (the `srcMissing` pattern above):
 * nothing to compare against, not a failure.
 */
describe('ShaderCarousel three build stays in sync with node_modules/three', () => {
  const THREE_BUILD = path.join(ROOT, 'node_modules/three/build');
  const CAROUSEL_THREE = path.join(ROOT, 'ShaderCarousel/lib/three');
  const FILES = ['three.core.min.js', 'three.tsl.min.js', 'three.webgpu.min.js'];
  const buildMissing = !existsSync(THREE_BUILD);

  for (const file of FILES) {
    it.skipIf(buildMissing)(
      `ShaderCarousel/lib/three/${file} is byte-identical to node_modules/three/build/${file}`,
      () => {
        const copy = path.join(CAROUSEL_THREE, file);
        const src = path.join(THREE_BUILD, file);
        expect(existsSync(copy), `carousel copy missing: ${copy}`).toBe(true);
        expect(existsSync(src), `three no longer ships ${file} — re-check the copy list`).toBe(true);
        expect(
          readFileSync(copy).equals(readFileSync(src)),
          `drift: ShaderCarousel/lib/three/${file} is not the installed three build. ` +
            'Re-copy it from node_modules/three/build (the benches must run the ' +
            'SAME renderer the app does, or the points they measure price a ' +
            'different runtime than the one the cost bar reports).',
        ).toBe(true);
      },
    );
  }
});

/**
 * The glTF decoders are the one vendored family whose source of truth is not
 * the submodule but THREE: `a-frame-shaderloader/js/decoders/` holds byte
 * copies of `node_modules/three/examples/jsm/libs` (the glTF Draco build,
 * meshopt, and the Basis Universal transcoder KTX2Loader runs), and loader 0.8
 * installs them on every GLTFLoader. The first describe above pins the
 * public/js copies to the submodule; this one pins the submodule to three, so a
 * three bump FAILS until they are re-copied (or the drift is deliberately
 * accepted) instead of shipping a decoder built for a different GLTFLoader —
 * and for the basis pair, a transcoder built for a different KTX2Loader worker
 * protocol, which would fail inside a Worker where nothing surfaces. The
 * README's table is pinned too, so the provenance it states (and the licence it
 * carries) cannot go stale beside the files.
 *
 * Skipped when node_modules/three or the submodule's decoders are absent (the
 * srcMissing pattern above): nothing to compare, not a failure.
 */
describe('the glTF decoders are three\'s own files, byte for byte', () => {
  const LIBS = path.join(ROOT, 'node_modules/three/examples/jsm/libs');
  const DECODERS = path.join(SRC, 'decoders');
  const FROM: Record<string, string> = {
    'draco_wasm_wrapper.js': 'draco/gltf/draco_wasm_wrapper.js',
    'draco_decoder.wasm': 'draco/gltf/draco_decoder.wasm',
    'meshopt_decoder.module.js': 'meshopt_decoder.module.js',
    'basis_transcoder.js': 'basis/basis_transcoder.js',
    'basis_transcoder.wasm': 'basis/basis_transcoder.wasm',
  };
  const skip = !existsSync(LIBS) || !existsSync(DECODERS);

  for (const [file, rel] of Object.entries(FROM)) {
    it.skipIf(skip)(`js/decoders/${file} is node_modules/three/examples/jsm/libs/${rel}`, () => {
      const src = path.join(LIBS, rel);
      expect(existsSync(src), `three no longer ships ${rel} — re-check the decoder list`).toBe(true);
      expect(
        readFileSync(path.join(DECODERS, file)).equals(readFileSync(src)),
        `drift: a-frame-shaderloader/js/decoders/${file} is not the installed three's ${rel}. ` +
          'Re-copy it (and update js/decoders/README.md), then push the submodule and purge it on jsdelivr.',
      ).toBe(true);
    });
  }

  it.skipIf(skip)('holds exactly those files plus the README', () => {
    expect(readdirSync(DECODERS).sort()).toEqual([...Object.keys(FROM), 'README.md'].sort());
  });

  it.skipIf(skip)('the README states the installed three, each file\'s size and sha256, and the Apache-2.0 text', () => {
    const readme = readFileSync(path.join(DECODERS, 'README.md'), 'utf8');
    const three = readFileSync(path.join(ROOT, 'node_modules/three/package.json'), 'utf8')
      .match(/"version":\s*"([^"]+)"/)?.[1];
    expect(three).toBeTruthy();
    expect(readme).toContain(`three ${three}`);
    for (const file of Object.keys(FROM)) {
      const bytes = readFileSync(path.join(DECODERS, file));
      const row = readme.split('\n').find((l) => l.startsWith(`| \`${file}\``));
      expect(row, `README has no row for ${file}`).toBeTruthy();
      expect(row).toContain(bytes.length.toLocaleString('en-US'));
      expect(row).toContain(createHash('sha256').update(bytes).digest('hex'));
    }
    // The Draco licence must travel with the files, whole.
    expect(readme).toContain('Apache License');
    expect(readme).toContain('TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION');
    expect(readme).toContain('END OF TERMS AND CONDITIONS');
  });
});
